# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    description: "Print workflow ID"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  get_workflow_id:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - print_pipeline_id

workflows:
  # Name the workflow "welcome"
  test:
    jobs:
      - get_workflow_id