# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_env:
    docker:
      - image: circleci/node:13.8.0
    environment:
      NAME: Hung
    steps:
      - run: echo $NAME
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt 
      - persist_to_workspace:
           root: ~/
           paths: 
            - output.tx
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: cat ~/output.txt 
      - attach_workspace:
           at: ~/
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file
        requires:
          - save_hello_world_output